# Use the official Python image with the latest version of Python 3.11
FROM python:3.11

# Set the timezone
ENV TZ=America/Lima
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Set environment variables
ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1

# Set the working directory
WORKDIR /code

# Copy requirements.txt to the container
COPY requirements.txt /code/  

# Install dependencies
RUN pip install -r requirements.txt

# Expose port 8080
EXPOSE 8080

# Start the server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8080"]
