version: '3.8'

services:
  database:
    image: postgres
    command: ["postgres", "-c", "max_connections=300", "-c", "shared_buffers=512MB"]
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    environment:
      - POSTGRES_DB=juzto_videos_audiencia
      - POSTGRES_USER=juzto
      - POSTGRES_PASSWORD=tiempo90
    ports:
      - "5433:5432"
      
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://juzto:tiempo90@database:5433/juzto_videos_audiencia

volumes:
  postgres_data:
