# Generated by Django 4.1.7 on 2023-04-16 02:33

from django.db import migrations, models
import reportarbugs.models


class Migration(migrations.Migration):

    dependencies = [
        ('reportarbugs', '0002_reporte_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', validators=[reportarbugs.models.Reporte.validate_file_size, reportarbugs.models.Reporte.validate_file_extension]),
        ),
    ]
