# Generated by Django 4.1.7 on 2023-04-16 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_upload', '0003_rename_video_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cedula',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Cedula invalida', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='video',
            name='id_audiencia',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='audiencia invalida', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='video',
            name='id_comparendo',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='comparendo invalida', regex='^[0-9]{10}$')]),
        ),
    ]
