# Generated by Django 4.1.7 on 2023-04-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_upload", "0004_alter_video_cedula_alter_video_id_audiencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_url",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
