# Generated by Django 4.1.7 on 2023-04-21 20:14

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("video_upload", "0005_alter_video_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="temp/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="id_audiencia",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="audiencia invalida", regex="^[a-zA-Z0-9_]*$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="id_comparendo",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="comparendo invalida", regex="^[a-zA-Z0-9_]*$"
                    )
                ],
            ),
        ),
    ]
